### PR TITLE
Globa anchor and tileset material samples

### LINKED ISSUE #5: Add globe anchors sample
Add a sample demonstrating how to use globe anchors, added in https://github.com/CesiumGS/cesium-omniverse/pull/453.

CC @weegeekps @r-veenstra

### LINKED ISSUE #6: Add tileset materials sample
Add a sample demonstrating how to use tileset materials. The example in https://github.com/CesiumGS/cesium-omniverse/pull/406#issuecomment-1771561788 might be a good place to start.

CC @r-veenstra

### LINKED ISSUE #7: Add tileset clipping example
Add tileset clipping example building off the work in https://github.com/CesiumGS/cesium-omniverse/pull/505. One of the open questions still is how to generate the texture mask, e.g. using Omniverse's drawing tools.

CC @r-veenstra

### PR DESCRIPTION
**Pull request by r-veenstra**
This PR contains three samples demonstrating new features of Cesium for Omniverse

Closes #5 by demonstrating 50 prims representing populations of US states individually anchored to their states lat/long.

image

Closes #6 by demonstrating an elevation heatmap blending with Cesium World Terrain and Bing Imagery

image

Closes #7 by demonstrating a road design clipped into a tileset.  Simultaneously demonstrates globe anchors too (however the clipping is not currently anchored and will be mis-aligned if the main Cesium Georeference changes)

image

### CODE REVIEW

**Comment by lilleyse** [comment]
@r-veenstra these looks great. I just had to fix the paths in TilesetClipping.usda: https://github.com/CesiumGS/cesium-omniverse-samples/pull/8/commits/cdd4c3c4db5442b2fa16ee3b43383474debdacdc

**Comment by lilleyse** [comment]
I wonder if ElevationHeatmap and TilesetClipping should be different folders... otherwise it's easy to miss the clipping example.

**Comment by lilleyse** [comment]
It might be worth using Git LFS for the textures

**Comment by lilleyse** [comment]
Out of curiosity, why does the globe anchors example use nested prims? Is that so the cylinder prim is easier to adjust? And is that a workflow we recommend?

CC @weegeekps.

**Comment by weegeekps** [comment]
I'm not sure why @r-veenstra chose to do so, but I don't see any issues with it. Honestly, I imagine that in some cases it would be better than directly attaching the anchor to the prim.

**Comment by weegeekps** [comment]
Also, why is the anchors demo using RTX Interactive mode rather than RTX Real Time? It absolutely destroys performance.

**Comment by r-veenstra** [comment]
> I'm not sure why @r-veenstra chose to do so, but I don't see any issues with it. Honestly, I imagine that in some cases it would be better than directly attaching the anchor to the prim.

In this example these prims are cylinders individually scaled to reflect population, and as their pivot is in their center of their mesh they need to be raised 50% of the prims height to sit correctly on the globe surface.  To do this with a single prim that includes a globe anchor gets a little messy as these changes need to be set within both the Transform:cesium matrix and the height value of the globe anchor.

**Comment by r-veenstra** [comment]
> Also, why is the anchors demo using RTX Interactive mode rather than RTX Real Time? It absolutely destroys performance.

I've switched it and the elevation demo to RTX Real-time.  Elevation demo is okay, but annoyingly RTX Real-time shadows appear to completely fail at long distances (eg. looking at the globe).  I'll do some more investigation into improving visuals, but won't let this hold up any releases.

**Comment by r-veenstra** [comment]
> I wonder if ElevationHeatmap and TilesetClipping should be different folders... otherwise it's easy to miss the clipping example.

I've moved clipping to its own folder

**Comment by r-veenstra** [comment]
> It might be worth using Git LFS for the textures

LFS should now be setup for the textures

**Pull request merged**
